### ISSUE TITLE
Error when I try to use travel.sqlite: chain.invoke({"question": "How many rows are there in the aircrafts_data table?"}) -> TypeError: must be real number, not str

### ISSUE THREAD

**Issue by Tran-Duc-Duy** [Farzad-R/Advanced-RAG-Series#8] opened 2024-10-24 20:20 UTC
Thank you very much for sharing your knowledge, everything is great, however, when I cloned it to my computer and tried to use it, I encountered some difficulties working with the .sqlite file.  

python 3.9 | window 11  

I get an error when I try to use travel.sqlite 
In the file **Advanced-QA-and-RAG-Series\AgentGraph-Intelligent-Q&A-and-RAG-System\Notebooks\Tools\sql_agents\sql_agent_steps.ipynb**

Maybe I downloaded the wrong database file ::(( https://www.kaggle.com/code/mpwolke/airlines-sqlite/input

`response = chain.invoke({"question": "How many rows are there in the aircrafts_data table?"})`   

 I always get the error:
 
```
 Cell In[28], [line 8](vscode-notebook-cell:?execution_count=28&line=8)
      [6](vscode-notebook-cell:?execution_count=28&line=6) write_query = create_sql_query_chain(llm, db)
      [7](vscode-notebook-cell:?execution_count=28&line=7) chain = write_query | get_query| execute_query
----> [8](vscode-notebook-cell:?execution_count=28&line=8) response = chain.invoke({"question": "How many rows are there in the aircrafts_data table?"})
      [9](vscode-notebook-cell:?execution_count=28&line=9) response = get_query(response)

File d:\miniconda\envs\rag39\lib\site-packages\langchain_core\runnables\base.py:2876, in RunnableSequence.invoke(self, input, config, **kwargs)
   [2874](file:///D:/miniconda/envs/rag39/lib/site-packages/langchain_core/runnables/base.py:2874) context.run(_set_config_context, config)
   [2875](file:///D:/miniconda/envs/rag39/lib/site-packages/langchain_core/runnables/base.py:2875) if i == 0:
-> [2876](file:///D:/miniconda/envs/rag39/lib/site-packages/langchain_core/runnables/base.py:2876)     input = context.run(step.invoke, input, config, **kwargs)
   [2877](file:///D:/miniconda/envs/rag39/lib/site-packages/langchain_core/runnables/base.py:2877) else:
   [2878](file:///D:/miniconda/envs/rag39/lib/site-packages/langchain_core/runnables/base.py:2878)     input = context.run(step.invoke, input, config)

File d:\miniconda\envs\rag39\lib\site-packages\langchain_core\runnables\passthrough.py:495, in RunnableAssign.invoke(self, input, config, **kwargs)
    [489](file:///D:/miniconda/envs/rag39/lib/site-packages/langchain_core/runnables/passthrough.py:489) def invoke(
    [490](file:///D:/miniconda/envs/rag39/lib/site-packages/langchain_core/runnables/passthrough.py:490)     self,
    [491](file:///D:/miniconda/envs/rag39/lib/site-packages/langchain_core/runnables/passthrough.py:491)     input: Dict[str, Any],
    [492](file:///D:/miniconda/envs/rag39/lib/site-packages/langchain_core/runnables/passthrough.py:492)     config: Optional[RunnableConfig] = None,
    [493](file:///D:/miniconda/envs/rag39/lib/site-packages/langchain_core/runnables/passthrough.py:493)     **kwargs: Any,
    [494](file:///D:/miniconda/envs/rag39/lib/site-packages/langchain_core/runnables/passthrough.py:494) ) -> Dict[str, Any]:
--> [495](file:///D:/miniconda/envs/rag39/lib/site-packages/langchain_core/runnables/passthrough.py:495)     return self._call_with_config(self._invoke, input, config, **kwargs)

File d:\miniconda\envs\rag39\lib\site-packages\langchain_core\runnables\base.py:1785, in Runnable._call_with_config(self, func, input, config, run_type, **kwargs)
...
File lib\\sqlalchemy\\cyextension\\resultproxy.pyx:79, in sqlalchemy.cyextension.resultproxy._apply_processors()

File lib\\sqlalchemy\\cyextension\\processors.pyx:68, in sqlalchemy.cyextension.processors.DecimalResultProcessor.process()

TypeError: must be real number, not str
 ```

**Comment by Farzad-R** [comment] 2024-10-24 22:52
Thank you. This error has happened to several users across different projects of mine in the last two weeks. I can’t reproduce it myself when I use the environments I set up during development. I believe it’s due to a new bug in LangChain’s backend. Some users said the error disappeared when they switched to a different database, so it seems to only affect certain ones. The exact cause is still unknown to me and I didn't have the time to dig deep and check LangChain's backend personally, but I’m hopeful it will be fixed soon. I didn’t have this issue when I was developing the projects. I am aiming to have a closer look during the weekend. Please let me know if you could figure out the cause before then.

**Closed as completed** 2024-11-07 02:06 UTC
